(require `deft)
(setq deft-extensions `("txt" "tex" "org"))
(setq deft-text-mode `org-mode)
(setq deft-directory "~/.deft")
(setq deft-recursive t)
;; (global-set-key [f9] `deft)
(setq deft-use-filename-as-title nil)
(setq deft-auto-save-buffers nil)
(setq deft-auto-save-interval 0)
(setq deft-time-format " %Y-%m-%d %H:%M")
(setq deft-file-naming-rules '((nospace . "_")
                               (case-fn . downcase)))

(setq deft-window-width (window-width))
(define-minor-mode deft-note-mode "Deft notes" nil " Deft-Notes" nil)
(setq deft-text-mode 'deft-note-mode)
(defun kill-all-deft-notes ()
  (interactive)
  (save-excursion
    (let((count 0))
      (dolist(buffer (buffer-list))
        (set-buffer buffer)
        (when (not (eq nil deft-note-mode))  
          (setq count (1+ count))
          (kill-buffer buffer)))
      )))
(defun deft-or-close () (interactive) (if (or (eq major-mode 'deft-mode) (not (eq nil deft-note-mode)))
                                          (progn (kill-all-deft-notes) (kill-buffer "*Deft*"))
                                        (deft)
                                        ))
(global-set-key [f9] 'deft-or-close)


